version: '3.9'
services:
  nginx:
    image: nginx:1.18
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./certbot_data:/letsencrypt
      - ./certbot_data/certs:/etc/letsencrypt      
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
  certbot:
    container_name: certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot_data:/letsencrypt
      - ./certbot_data/certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 13h & wait $${!}; done;'"
